name: CI

on: [push]

defaults:
    run:
        shell: bash

jobs:
    build_and_test:
        strategy:
            fail-fast: false
            matrix:
                os: [windows-latest, ubuntu-latest, macos-latest]
                include:
                  - os: windows-latest
                    bin: unit_tests.exe
                    dir: ./Debug/
                  - os: ubuntu-latest
                    bin: unit_tests
                    dir: ./
                  - os: macos-latest
                    bin: unit_tests
                    dir: ./

        name: ${{ matrix.os }}
        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v2

            - name: Generate Build File
              run: cmake . -B build

            - name: Build Project
              run: cmake --build build

            - name: Generate Tests Build File
              run: cmake . -B build_tests -DUNIT_TESTS=ON

            - name: Build Unit Tests
              run: cmake --build build_tests

            - name: Run Unit Tests
              run: ${{ matrix.dir }}${{ matrix.bin }}

    memory_check:
        name: memory_check
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Generate Tests Build File
              run: cmake . -B build_tests -DUNIT_TESTS=ON

            - name: Build Unit Tests
              run: cmake --build build_tests

            - name: Run Unit Tests with Valgrind
              run: valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --error-exitcode=1 ./unit_tests